manifest = "e70399ed8339e23b23c0267af5c10e8baabfbac18f30f3715db628ed05e9e6b0"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[dependency]]
package = "github.com/buckaroo-pm/xz"
target = "//src/liblzma:lzma"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "branch=master" ]
revision = "76044bba206818f3378c346396f4a33de338d71c"

[lock."github.com/buckaroo-pm/xz"]
versions = [ "branch=master" ]
revision = "593cc1510a5b0f62d0d2167bdd57d36182a0cf35"
